### ISSUE TITLE
failed to deploy next.js to azure app service

### ISSUE THREAD

**Issue by XYjourney** [microsoft/Oryx#1192]
### Bug Report
I got this error  when i deploy next.js to web app service secondly after the first successful deployment. It sayed had no permission when rename a file.
`下午5:26:18 officeplusweb1: rsync: rename "/home/site/wwwroot/.next/.trace.qMaBhd" -> ".next/trace": Permission denied (13)
下午5:26:18 officeplusweb1: rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]`

![image](https://user-images.githubusercontent.com/18476675/147744421-7607981c-5b93-408a-9767-2bfe2f4dc023.png)

**Comment by XYjourney** [comment]
any body help ?

**Comment by gpcastro** [comment]
This is likely a file locking problem. Your app might be opening files inside `.next/trace` folder, which is also part of your deployment - so the running app and the deployment process are both trying to write to that file. 

You can try using deployment slots, temporarily stop your app during deployment, or - the ideal option - not use the web app file system to store state and rely on storage resource to do it.

**Comment by BarreraSlzr** [comment]
As @gpcastro says you should stop your application (Azure Service) because that trace folder is used by the previous development slot so azure should be able to edit this folder, once your deployment is successful you only need to start again

**Comment by qianz2** [comment]
@XYjourney Is it still an issue or it's resolved? Please close it if it's resolved. thanks!

**Comment by AndyRace** [comment]
@XYjourney did you ever resolve this because I'm getting exactly the same!

I'm deploying to a Linux slot which I stop before doing a zip deploy.
I've re-created the slot, deployed successfully but the subsequent deployment fails with exactly the same error here.

My suspicion is that I have a custom bash startup script (which eventually runs 'yarn dev') - removing this and trying again doesn't help but I suspect the damage has already been done.

I'm wondering if stopping the service is not successfully killing the running (Next) node app so it's leaving .next/trace in use.
I've tried using Kudu console's bash to diagnose the issue.

The file .next/trace does exist but the kudu_ssh_user isn't able to access it (cat or rm).
>> -rwxrwxrwx 1 nobody nogroup 14934 Oct  8 18:33 trace
ps -ax doesn't show anything obvious (was hoping for a node or yarn to be running that I could kill).

I can't find which process is keeping it open -- perhaps someone can point me in the right direction.

Any help would be very appreciated because this is making it impossible to deploy twice.

**Comment by sbdev001** [comment]
I am getting this same issue with rsync. I see the recommendation to stop your app from locking the file being written to. I don't understand how is it even a real solution - isn't it equivalent to a forced outage on your service. Does someone have a more reasonable solution without stopping the service. The other solution regarding using a storage service - you have to write to the file system before we move the logs to the storage service so wouldn't it run into the same issue?

**Comment by sbdev001** [comment]
If it is of help to other folks - our file that was giving the error was in .gitignore. The file was being generated during the build phase while running the tests. So, we just added a step to delete the file after running the tests. That made the error go away.

**Comment by simonjj** [comment]
Closing this issue since it seems resolved. If this should become relevant again please open an issue in https://github.com/projectkudu/kudu as this is the component that ultimately is responsible for packaging and deployment for App Service and Functions. Oryx is purely responsible for building.
