### ISSUE TITLE
Add outbound dependencies documentation for oryx remote build.

### ISSUE THREAD

**Issue by Catastrophe1** [microsoft/Oryx#1454]
### Feature Request

We noticed that there are a few outbound dependencies required by oryx during remote build on app service like https://oryx-cdn.microsoft.io/

Some customers use VNet integration with firewall to control the outbound traffic of the app service. Blocking the outbound dependencies will cause the remote build fail. Can we add the documentation around what endpoints need to be opened in order for a successful build? Thank you.

**Comment by cormacpayne** [comment]
@Catastrophe1 Hey there -- this is a good point to bring up, I don't believe we have documentation easily accessible to users that outline what this CDN is used for. For quick context: this CDN points to our storage account where previously package platform binaries are located so that Oryx can easily pull them down into the container to build the user's application after Oryx identifies what platform and platform version the application is targeting. I'll add a work item on our side to update our documentation, starting with the `README.md` at the root of our repository, but if there's another location you feel would be ideal to have this documentation accessible, please let me know.

**Comment by Catastrophe1** [comment]
Hi @cormacpayne! That will be great to add in the readme. Appreciate your response.

**Comment by mrjacklu** [comment]
bump -- ran into this exact issue building my function remotely yesterday. What endpoints do we need to allow outbound traffic? We are using Azure App Service with VENT integration as well. Thanks.

**Comment by Catastrophe1** [comment]
> bump -- ran into this exact issue building my function remotely yesterday. What endpoints do we need to allow outbound traffic? We are using Azure App Service with VENT integration as well. Thanks.

Hi @mrjacklu  Please allow outbound HTTP/S connection to https://oryx-cdn.microsoft.io/ in the firewall settings

**Comment by pauld-msft** [comment]
Hi all, we now have [some documentation](https://github.com/microsoft/Oryx/blob/main/doc/hosts/appservice.md#network-dependencies) that outlines the network dependencies for Oryx. Pasting the blurb here as well:  

> When using App Service with a Virtual Network or an App Service Environment, you will need to allow outbound access from the webapp to oryx-cdn.microsoft.io on port 443. oryx-cdn.microsoft.io hosts the Oryx packages corresponding to each SDK language and version. If this network dependency is blocked, then App Service will not be able to build your application using Oryx.
