### ISSUE TITLE
Add Ruby 3.2 support

### ISSUE THREAD

**Issue by olbrich** [microsoft/Oryx#1779]
### Feature Request

Ruby 3.2.0 was officially [released](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/), please add support for it.

**Comment by pauld-msft** [comment]
Hi @olbrich, as new minor versions take more effort than patches, this will need to be prioritized accordingly. I will create a ticket to track this work, but just want to give a heads up that this will probably take some time for us to do and then it will need to be rolled out to our partners' platforms (e.g. Azure App Service, Static Web Apps, etc.)

**Comment by olbrich** [comment]
@pauld-msft Thanks!

**Comment by aussiDavid** [comment]
@pauld-msft  has there been any movement on supporting ruby `3.2.x`? Thanks.

**Comment by pauld-msft** [comment]
Hello both! Apologies for the lack of communication here. We ended up removing this from our backlog due to the retirement of Ruby support in App Service, who is our main partner and the driving factor for many of our updates. https://azure.microsoft.com/en-us/updates/rubysupport/

`Ruby 2.7 support is ending on 12 April 2023. After this date, App Service won’t support Ruby 2.7 or future versions of Ruby. Your applications will continue to run unchanged but won’t receive patches after 12 April 2023.`

I'm sorry for any inconvenience that comes from not getting the latest Ruby versions through App Service. If you would like to get the latest versions, you can migrate the application to a custom container using the [documentation provided here](https://github.com/Azure/app-service-linux-docs/blob/master/HowTo/use_ruby_with_container.md#how-to-run-ruby-on-rails-custom-container-on-app-service).

**Comment by aussiDavid** [comment]
Ok. Thank you.

**Comment by pauld-msft** [comment]
@olbrich - So from what I can tell, static web apps does not support ruby natively: https://learn.microsoft.com/en-us/azure/static-web-apps/languages-runtimes#api

If your api is Ruby, then you could potentially follow the docs I linked above to migrating to a custom container on app service for the API, and following the docs [here](https://learn.microsoft.com/en-us/azure/static-web-apps/apis-app-service) to hook it up to the frontend. 

You can also look at doing the same with Azure Container Apps as described in https://learn.microsoft.com/en-us/azure/static-web-apps/apis-container-apps.
