### ISSUE TITLE
Oryx is using a  node.js version other than specified in package.json

### ISSUE THREAD

**Issue by naricc** [microsoft/Oryx#1951]
I am tryign to use gihub actions to build for an azure static web app. Building requires node >18.0.0, and I specified in that in the package.json: https://github.com/naricc/demosite/blob/16da283999968a0e08a5f08c4b05571ff1d8ca18/package.json#L41

However, when I look at the build (https://github.com/naricc/demosite/actions/runs/4570681521/jobs/8098336018) I see this:

```
Detected following platforms:
  nodejs: 16.19.0
Version '16.19.0' of platform 'nodejs' is not installed. Generating script to install it...
```
And then later it fails with:

```
error Gatsby requires Node.js 18.0.0 or higher (you have v16.19.0).
```

Is this a bug in oryx? Or have I misunderstood how to specify the node version?

**Comment by william-msft** [comment]
Hi @naricc , thank you for reaching out. It seems the provided `package.json` is missing a comma on [line 39](https://github.com/naricc/demosite/blob/16da283999968a0e08a5f08c4b05571ff1d8ca18/package.json#L39). Since the missing comma is right before the `engines` field, this would cause an issue.

**Comment by naricc** [comment]
> Hi @naricc , thank you for reaching out. It seems the provided `package.json` is missing a comma on [line 39](https://github.com/naricc/demosite/blob/16da283999968a0e08a5f08c4b05571ff1d8ca18/package.json#L39). Since the missing comma is right before the `engines` field, this would cause an issue.

Thanks. I fixed the comma: https://github.com/naricc/demosite/blob/ff218abac60e30bc6006dcaa07e465721f1b005c/package.json#L39, but the same error seems to be happening

**Comment by william-msft** [comment]
@danv-msft do you know which image azure static webapps use?

Side note:
I was able to build successfully locally which Jamstack:
![image](https://user-images.githubusercontent.com/86327553/230696386-ab35d240-84cd-4284-af5d-7e06848a084c.png)

The Docker image in the logs looks like its [from November 3, 2022.](https://github.com/naricc/demosite/actions/runs/4570681521/jobs/8098336018#step:4:22) Which should be fine since [this feature ](https://github.com/microsoft/Oryx/pull/1392)was released back in May 2022.

**Comment by simonjj** [comment]
We're closing this issue due to its age. If this is still impacting you please open a new issue and simply link back to this one.
