### ISSUE TITLE
Oryx build fails for nodejs app when code is in github subfolder

### ISSUE THREAD

**Issue by cljung** [microsoft/Oryx#2253]
### Bug Report

- At what date and time did you most recently experience the problem?
2023-11-13 06.48 UTC

- Where did you experience the problem? E.g. Azure Web Apps, Azure Functions, Azure Container Registry, or offline use.
Azure Web App

- If your repo is publicly available please share its URL:
ARM template used - https://portal.azure.com/#create/Microsoft.Template/uri/https%3a%2F%2Fcljungdevdideu.z6.web.core.windows.net%2Ftemplate.json
github repo that works - https://github.com/Azure-Samples/nodejs-docs-hello-world.git
github repo that fails - https://github.com/Azure-Samples/active-directory-verifiable-credentials-node.git
code is in subfolder '1-node-api-idtokenhint' and this name is used as PROJECT parameter when deploying

- What happened?
With the repo that works, code is in root folder and oryx build succeeds. With the repo that fails, code is in subfolder '1-node-api-idtokenhint' (which is passed as PROJECT parameter to ARM template). Oryx build defaults to Dotnet build and fails.

- What did you expect or want to happen?
That you are able to pass a subfolder name so that you can build a subfolder and have it copied to /home/site/wwwroot

- How can we reproduce it?
Use the ARM template link above and specify 1) the failing github repo link and 2) 1-node-api-idtokenhint for Project parameter

- Do you have log output? Please include between the backticks:

```
Command: oryx build /home/site/repository -o /home/site/wwwroot --platform nodejs --platform-version 18 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8dbe412d31a9e42 -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log
Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20230508.1, Commit: 7fe2bf39b357dd68572b438a85ca50b5ecfb4592, ReleaseTagName: 20230508.1

Build Operation ID: 61dc1862872a8be9
Repository Commit : ddb72bac8719ff08a6d883693c8512480b269e98
OS Type           : bullseye
Image Type        : githubactions

Detecting platforms...
Error: Could not find the .NET Core project file.
Error: Could not find the .NET Core project file.\n/bin/bash -c "oryx build /home/site/repository -o /home/site/wwwroot --platform nodejs --platform-version 18 -p virtualenv_name= --log-file /tmp/build-debug.log  -i /tmp/8dbe412d31a9e42 -p compress_node_modules=tar-gz | tee /tmp/oryx-build.log ; exit $PIPESTATUS "
```

**Comment by cormacpayne** [comment]
@cljung Hey Christer, thanks for filing this issue -- it appears that even though the call to `oryx build` is being provided the `--platform nodejs` argument, we're still going through all of our possible platform detectors and hitting the exception that you're seeing in our .NET detector due to the presence of the `PROJECT` environment variable (which is what you're setting to the relative path in your repository). This `PROJECT` environment variable is only valid for .NET projects, so it's interesting that it's popping up in this ARM template without any specific mention of .NET.

Unfortunately, for other platforms, relative folders within a GitHub repository are not currently supported, so even removing this `PROJECT` environment variable will still cause the build to fail since it's not able to find your Node project from the root of the repository, and there's currently no way to point to a subdirectory in the provided GitHub repository. The only remediation I have at the moment is to refactor the repository such that this application is found at the root of the repository.

If there's any documentation that you've been following that has influenced how you're filling out this ARM template or says anything about relative paths in a GitHub repository, I'd love to check those out just to make sure we're not missing anything or that there's any misguidance from our side. Thanks!

**Comment by cljung** [comment]
@cormacpayne - I've found this workaround that works for subfolders. You disable build systems via ENABLE_ORYX_BUILD=false and SCM_DO_BUILD_DURING_DEPLOYMENT=false and then do the build yourself with an appCommandLine like below. It's not a nice solution, but it works. Refactoring a github repo due to limitations in the Oryx build system is not an option for me or for most solutions I suspect. It would be great if support for subfolders could be added to the product backlog.
 
"appCommandLine": "[concat('cd /home/site/wwwroot && cp -r /home/site/repository/', parameters('Project'), '/* . && npm install && npm run start')]",

**Comment by simonjj** [comment]
This issue seems resolved. Will be closing this issue. If this is still relevant and impacting you please open a new issue and link back to this issue for reference.
