### ISSUE TITLE
Oryx did npm run build but not using build folder

### ISSUE THREAD

**Issue by robi-ng** [microsoft/Oryx#449]
Hi,
I'm trying to deploy react app to Azure App Service Linux instance. It's using Microsoft Oryx in the deployment, and correctly executing "npm run build" to generate React production files and copy all the files to /home/site/wwwroot, however the web server is not using the "build" folder to serve content. How can I configure it to use the "build" folder? (default React production folder)

**Comment by arroyc** [comment]
Hi @robi-ng thanks for reporting, will you be please able to provide little more context? From your description my primary assumption is we need to configure the app so that it knows where is the "build" folder. Can you please verify if "build" folder resides in /home/site/wwwroot. Also it would be nice if you can share a sample repro app for this issue.

**Comment by robi-ng** [comment]
Hi @arroyc yes "build" folder resides in /home/site/wwwroot. I found the option on Azure portal, Configuration > General settings > Setup Command, to configure my startup command "npx serve -s build" so that it doesn't use the default "npm start" (meant for React development environment).

**Comment by arroyc** [comment]
Thank you for sharing @robi-ng .. hopefully things are resolved at your end .. please let us know for any future issues.
