### ISSUE TITLE
Support for hugo extended binaries (Docsy)

### ISSUE THREAD

**Issue by timeu** [microsoft/Oryx#601]
### Feature Request

[Docsy](https://www.docsy.dev/docs/getting-started/) requires the extended version of hugo to work properly. Currently only the regular hugo binary is available and thus doscy themed hugo pages fail to build. 
Additionally docsy requires autoprefixer and postcss-cli to be installed to build the final CSS resources.

**Comment by kichalla** [comment]
Thanks @timeu ..Oryx currently has 0.59.1 version of Hugo and based on the documentation [here](https://www.docsy.dev/docs/getting-started/#install-hugo), it appears this version should be good enough. And regarding `autoprefixer` and `postcss-cli`, [this](https://www.docsy.dev/docs/getting-started/#install-postcss) link appears to indicate that `autoprefixer` will not work unless it is a local npm install. Considering all these, can you add a `package.json` to your hugo project so that you can install these 2 dependencies and as part of the `scripts:build` action in package.json, you can kick off `hugo`

cc @miwebst

**Comment by timeu** [comment]
Hi @kichalla 
thanks for the quick response. 
Thanks for the `package.json` suggestion. I will give it a try. 
The hugo version should be fine, however docsy requires the `extended` hugo binary. 
My github action task failed with following error:

```
Source directory     : /bin/staticsites/ss-oryx/app-int
Destination directory: /bin/staticsites/ss-oryx/app


Using Hugo version:
Hugo Static Site Generator v0.59.1-D5DAB232 linux/amd64 BuildDate: 2019-10-31T15:21:02Z

Building sites … ERROR 2020/05/20 09:22:18 Failed to read Git log: Git executable not found in $PATH
ERROR 2020/05/20 09:22:18 Transformation failed: TOCSS: failed to transform "scss/main.scss" (text/x-scss): this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Error: Error building site: logged 2 error(s)
Total in 3171 ms
```

**Comment by kichalla** [comment]
Thanks @timeu We will look into it and will update you

**Comment by timeu** [comment]
FYI: I found this workaround for my issue: https://github.com/microsoft/Oryx/issues/615#issuecomment-633655882

**Comment by kichalla** [comment]
@timeu This issue has been fixed. Please try again and let us know if you still see the issue.
