### ISSUE TITLE
Every deployment needs to download Python 3.8 again

### ISSUE THREAD

**Issue by empz** [microsoft/Oryx#902]
I've created a Linux Python Azure Function v3 (setting python version to 3.8). 

Everytime I deploy to this function app, the build has to re-download Python 3.8.6

```
Detecting platforms...
Detected following platforms:
  python: 3.8.6
Version '3.8.6' of platform 'python' is not installed. Generating script to install it...
Source directory     : /tmp/zipdeploy/extracted
Destination directory: /home/site/wwwroot
Downloading and extracting 'python' version '3.8.6' to '/tmp/oryx/platforms/python/3.8.6'...
Downloaded in 4 sec(s).
Verifying checksum...
Extracting contents...
Done in 16 sec(s).
Python Version: /tmp/oryx/platforms/python/3.8.6/bin/python3.8
```

Can we have this aligned with the Function App python version? Or at least have all the versions supported by Azure Functions already available to use during deployment?

**Comment by qianz2** [comment]
Hi @empz, the build image it's using is jamstack, and we aim to keep the image minimal so we didn't include python 3.8.6 into the image. It'll dynamically install python 3.8.6 sdks while building the apps. 
After the sdk was downloaded first time, it should not re-download again. For example, here is the logging info while I try to build the app second time.
I don't know if this is because you're using the old oryx version or Azure function didn't update Oryx latest release.

`2021-01-15 19:53:31.4942|DEBUG|Microsoft.Oryx.BuildScriptGenerator.Python.PythonPlatformInstaller|Version 3.8.6 is already installed at directory /tmp/oryx/platforms/python
2021-01-15 19:53:31.4942|DEBUG|Microsoft.Oryx.BuildScriptGenerator.Python.PythonPlatform|Python version 3.8.6 is already installed. So skipping installing it again.`

**Comment by empz** [comment]
That is not what I get every time I deploy the function.


Is this Oryx Version supposed to not re-download again? 
```
21:15:48 pa-dev-data-logs-ingestion: Running oryx build...
21:15:48 pa-dev-data-logs-ingestion: Command: oryx build /tmp/zipdeploy/extracted -o /home/site/wwwroot --platform python --platform-version 3.8 -p packagedir=.python_packages/lib/site-packages
21:15:52 pa-dev-data-logs-ingestion: Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
21:15:52 pa-dev-data-logs-ingestion: You can report issues at https://github.com/Microsoft/Oryx/issues
21:15:52 pa-dev-data-logs-ingestion: Oryx Version: 0.2.20201015.1, Commit: 1a35fbce482b20b71290f3a837a3469803ce4b44, ReleaseTagName: 20201015.1
21:15:52 pa-dev-data-logs-ingestion: Build Operation ID: |lYoAjjMOzo8=.19f6556b_
21:15:52 pa-dev-data-logs-ingestion: Repository Commit : 3b8a509144f64814bb5e90468940d480
21:15:52 pa-dev-data-logs-ingestion: Detecting platforms...
21:15:55 pa-dev-data-logs-ingestion: Detected following platforms:
21:15:55 pa-dev-data-logs-ingestion:   python: 3.8.6
21:15:55 pa-dev-data-logs-ingestion: Version '3.8.6' of platform 'python' is not installed. Generating script to install it...
21:15:55 pa-dev-data-logs-ingestion: Source directory     : /tmp/zipdeploy/extracted
21:15:55 pa-dev-data-logs-ingestion: Destination directory: /home/site/wwwroot
21:15:55 pa-dev-data-logs-ingestion: Downloading and extracting 'python' version '3.8.6' to '/tmp/oryx/platforms/python/3.8.6'...
```

Anyway, I think the each build is done on a fresh image so there's no persistent storage here.

**Comment by arroyc** [comment]
@empz ... you are  right about each build run on new instance, so it's not persistent. Also the image doesnt have 3.8 by default ... so everytime you trigger a new build in a new instance it needs to get downloaded and installed. Hope this helps ... I'm closing the issue for now. Please feel free to create a new issue if you are having troubles
